<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260213120823 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        if ($this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform) {
            $this->addSql('CREATE TABLE site_setting (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, value TEXT DEFAULT NULL, PRIMARY KEY (id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_64D05A535E237E06 ON site_setting (name)');
        } else {
            $this->addSql('CREATE TABLE site_setting (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, value TEXT DEFAULT NULL, UNIQUE INDEX UNIQ_64D05A535E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        }
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE site_setting');
    }
}
